### ISSUE TITLE
Use in Glide

### ISSUE THREAD

**Issue by tellfa** [Piasy/BigImageViewer#1]
Can we use this library with Glide ?

**Comment by Piasy** [comment]
Currently, the answer is no, because it use Fresco as image load library. But it's easy to make it work with other image load libraries, such as Glide, Picasso.

I just checked my schedule, I can add this feature before next week, with a relatively big refactor. 

I'm planing to extract the image cache and load function implementation out of the big image view module, so that we can use different image load library separately.

**Comment by Piasy** [comment]
@tellfa Hi, I just finish the refactor, adding support for glide should be very easy, I'll add it later this week :)

**Comment by Piasy** [comment]
Added since v1.1.1

**Comment by Piasy** [comment]
@tellfa  Besides, since the new artifact haven't been sync to jcenter, you may need add maven repo as below, but it should be synced soon:

``` gradle
maven {
    url "http://dl.bintray.com/piasy/maven"
}
```

**Comment by tellfa** [comment]
WoW! thans @Piasy for add glide library! ❤️ 
When you added other TODO list? this list is very great 😍
