### ISSUE TITLE
Why minSdkVersion = 16?

### ISSUE THREAD

**Issue by Swisyn** [Piasy/BigImageViewer#15]
First of all, thank you for this great lib! 

I'd like to use it in my project, but the problem is that minSdkVersion has set to 16. I've copied classes into my project which requires minSdkVersion = 15 and there is no errors? There is mess around after self copying classes rather than aar.

Could you please support older minSdkVersion as much as possible?

**Comment by Piasy** [comment]
Actually that's because API 16 is the default minSdkVersion in project created by AndroidStudio 2.2, and I see that [devices below API 16 is less than 3.4%](https://developer.android.com/about/dashboards/index.html#Platform).

But it will be ok to support lower API version, if SSIV, Fresco, Glide support that. Feel free to open a pr for that :)

**Comment by Swisyn** [comment]
Thank you for the answer. 

Yes, you're right about devices below api 16 but sometimes it gets useful to support for these devices :)

I've checked fresco which supports MIN_SDK_VERSION=9 and the glide is MIN_SDK_VERSION=10, don't have an idea if its supported by the picasso also supports  minSdkVersion = 14

gonna make a pr.

**Comment by love-311** [comment]
Hello, thank you very much for your open source library, it's lovely, but I think you ought to its support to the API14, because you this library is fully support API14 above, hope you can upload a new version of the support to API14,  Thank you.

**Comment by Piasy** [comment]
@love-311 There is a pr #17 for it. Gonna merge it and release a new version in 10 mins. :)

**Comment by Piasy** [comment]
try `1.2.2`
